### ISSUE TITLE
current_user & grape helper

### ISSUE THREAD

**Issue by syntaxTerr0r** [ruby-grape/grape-active_model_serializers#22]
Hi,

As i'm trying to access to my `current_user` helper from a serializer, it appears my serializer can't find the method. My helper works great in Grape context and is very basic:

``` ruby
module UserHelpers
  extend Grape::API::Helpers

  def current_user
    @current_user
  end
end
```

The documentation way don't seems to work either:

``` ruby
helpers do 
  def current_user
    @current_user
  end
end
```

... And my instance variable @current_user can't be accessed from a serializer, too.

Does this feature really works or was removed in active_models_serializers 0.9.1 ? Can't find a clue in this gem codebase nor in active_models_serializers codebase.

I would be happy to fix it in the gem, but can't find how.

**Comment by aaronklaassen** [comment]
@jrhe Why did this get closed? Still seems to be a problem in v1.3.2.

**Comment by syntaxTerr0r** [comment]
Yeah, problem's still here, hacked this way to make it work :

All my serializers inherit from this.

```
class BaseSerializer < ActiveModel::Serializer
  delegate :current_user, to: :scope
end
```

Require this helpers in specs :

```
  def serializer_scope(user)
    fakeScope = Struct.new(:user_object) do
      def current_user
        user_object
      end
    end
    fakeScope.new(user)
  end
```

Usage is as follow in rspec (to compare API response with) :

```
CompanySerializer.new(company, scope: serializer_scope(scope), root: false)
```


2015-06-15 18:29 GMT+02:00 Aaron Klaassen <notifications@github.com>:

**Comment by dblock** [comment]
@syntaxTerr0r This is still a problem on HEAD? Can you please reopen/open an issue?

**Comment by syntaxTerr0r** [comment]
@dblock I'm on grape-active_model_serializers 1.3.2, let me check on HEAD.

**Comment by xiaok** [comment]
still a problem there

**Comment by dblock** [comment]
@xiaok on HEAD?

**Comment by xiaok** [comment]
@dblock yes , current_user can't be accessed from  serializers.

then I found this issue , I used ``` delegate :current_user, to: :scope ```

caused an error "BaseSerializer#current_user delegated to scope.current_user, but scope is nil"

**Comment by dblock** [comment]
@xiaok If you think that's a bug, open a new one please?
