### ISSUE TITLE
Optional parameters for serializer

### ISSUE THREAD

**Issue by kris** [ruby-grape/grape-active_model_serializers#43]
Hi,

I'm in a position where I need to pass additional parameters to the serializer. I pull a collection of locations, and for each item, I need to show the distance from that requests IP to the Location object. The problem is the only way I can see to do this is something like:

```
locations.each do |location|
    location.source_coords = [lat, lng]
end
locations
```

The problem is that it's not the Location objects responsibility to deal with this, it's more the responsibility of the serializer. How can I pass the param to the serializer?

Thanks

**Comment by pkrefta** [comment]
+1

**Comment by dblock** [comment]
Don't know from the top of my head, but we should figure this one out.

**Comment by siong1987** [comment]
`grape-active_model_serializers` depends on `active_model_serializers`.  Shouldn't this be something that `active_model_serializers` should worry about?

**Comment by MoonShining** [comment]
+1

**Comment by drn** [comment]
This is a super old thread, so I'm going to close this now.
Though it might not be exactly what you were looking for, ASM supports this type of conditional rendering of serialized data via the fields functionality: https://github.com/rails-api/active_model_serializers/blob/master/docs/general/fields.md
