### ISSUE TITLE
Changing adapter in AMS is not affected to output

### ISSUE THREAD

**Issue by bypotatoes** [ruby-grape/grape-active_model_serializers#52]
**active_model_serializers-0.10.0**
**grape-active_model_serializers (1.3.2)**

I'd like to have `:json` as the default adapter for AMS, so I've initialized it: 
```
ActiveModelSerializers.config.adapter = :json
```
But nothing was changed and I've started looking into source.
As I've found grape-AMS using `serializer.new` [here](https://github.com/ruby-grape/grape-active_model_serializers/blob/master/lib/grape-active_model_serializers/formatter.rb#L29) to create serialized_resource. But this approach does not allow us to apply adapter, include meta etc. For that we should user `ActiveModelSerializers::SerializableResource` as [here](https://github.com/rails-api/active_model_serializers/blob/0fed4869df2a930ca7b0aebfcd66a3c0afd43a36/lib/grape/formatters/active_model_serializers.rb#L13).

**Comment by dblock** [comment]
This seems sensible, we'd take a pull request.

**Comment by fogisland** [comment]
Hello, is there any progress about this issue? I wanna AMS to generate json-api but it not works:
```
ActiveModelSerializers.config.adapter = :json_api
```
Thanks!

**Comment by dblock** [comment]
@fogisland I am not working on it.

**Comment by drn** [comment]
@bypotatoes & @fogisland - can you try to run this against master? I merged in a few commits that should solve this issue.

**Comment by drn** [comment]
closing this as this should be fixed on master. please reopen if it is not

**Comment by ouabing** [comment]
Hi guys, would you please bump the version so we can use a fixed version of gem to solve the problem? Using master source for our production is somewhat risky I think. Thanks!

**Comment by drn** [comment]
I was planning on doing some work before we released 1.5.0 but I can take care of that sometime this week and release a version. I'll post an update here when I push up a release

**Comment by ouabing** [comment]
@drn Thank you!

**Comment by drn** [comment]
@ouabing - [v1.5.0](https://rubygems.org/gems/grape-active_model_serializers/versions/1.5.0) has been released
