### ISSUE TITLE
Globally specify serialization adapter

### ISSUE THREAD

**Issue by phuongnd08** [ruby-grape/grape-active_model_serializers#66]
I want to use `:json` adapter globally. How can I do that?

**Comment by drn** [comment]
You can set this in an initializer:
`ActiveModelSerializers.config.adapter = :json`

grape-active_model_serializers uses whatever adapter is configured for ASM
https://github.com/rails-api/active_model_serializers#high-level-behavior

Here is a list of other adapters you can use: https://github.com/rails-api/active_model_serializers/tree/master/lib/active_model_serializers/adapter
