### ISSUE TITLE
Release v. next

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape-active_model_serializers#67]
Anyone wants to do it? @siong1987 @jrhe ?

**Comment by drn** [comment]
Sure, I'm happy to do it. Before that happens though, I think I need to dig into a bug I might have introduced to master when I made those refactoring changes a few months back. Can you give me a couple days to work on it? I'll check it out this weekend. Getting slammed at work these days

**Comment by dblock** [comment]
What am I paying you for?!  :)

Sure.

**Comment by drn** [comment]
:) 👍

**Comment by drn** [comment]
I'll do a release after https://github.com/ruby-grape/grape-active_model_serializers/pull/71 and https://github.com/ruby-grape/grape-active_model_serializers/pull/73 are out

**Comment by drn** [comment]
[v1.5.1](https://rubygems.org/gems/grape-active_model_serializers/versions/1.5.1) has been released
