### ISSUE TITLE
`include: '**'` option not working on serailizers

### ISSUE THREAD

**Issue by JWesorick** [ruby-grape/grape-active_model_serializers#69]
Per rails-api/active_model_serializers#2081 I'm trying to include all levels for one of my endpoints. But it seems the `includes` option isn't working with this gem.

**Comment by drn** [comment]
@JWesorick, are you using v1.5.0, master, or another version? Should be an easy fix, but that info would help point us in the right direction

**Comment by JWesorick** [comment]
v1.5.0

**Comment by drn** [comment]
Got it - I'll dig

**Comment by drn** [comment]
@JWesorick - can you try out these changes? https://github.com/ruby-grape/grape-active_model_serializers/pull/73
```
gem 'grape-active_model_serializers',
  github: 'ruby-grape/grape-active_model_serializers',
  branch: 'pass-ams-options'
```

**Comment by JWesorick** [comment]
@drn Yep that works!

**Comment by drn** [comment]
Awesome, sorry for the delay. Been hectic at work. I'll get this merged in sometime over the next few days and release a new gem version

**Comment by JWesorick** [comment]
Thanks!

**Comment by drn** [comment]
[v1.5.1](https://rubygems.org/gems/grape-active_model_serializers/versions/1.5.1) has been released!
